DELETE https://graph.microsoft.com/v1.0/schemaExtensions/inheritscloud_SocialData HTTP/1.1

GET https://graph.microsoft.com/v1.0/schemaExtensions HTTP/1.1

POST https://graph.microsoft.com/v1.0/schemaExtensions HTTP/1.1
content-type: application/json
{
    "id": "inheritscloud_SocialData",
    "description": "Adding social networks data to users",
    "owner": "ac638f16-63c2-462b-95a4-16f8a60b0628",
    "targetTypes": [
        "User"
    ],
    "properties": [
        {
            "name": "twitter", "type": "String"
        },
        {
            "name": "facebook", "type": "String"
        },
        {
            "name": "lastEvent", "type": "DateTime"
        },
        {
            "name": "isSpeaker", "type": "Boolean"
        }
    ]
}

PATCH https://graph.microsoft.com/v1.0/users/42ff1ed5-11d4-4e79-95bf-8df97611dfe1 HTTP/1.1
{
    "inheritscloud_SocialData": {
        "twitter": "@tioben",
        "facebook": "facebook.com/tioben",
        "lastEvent": "2018-06-09T10:30:00",
        "isSpeaker": true
    }
}

PATCH https://graph.microsoft.com/v1.0/users/dfcdcaa2-55b7-4efb-9ae1-5fd176f08b38 HTTP/1.1
{
    "inheritscloud_SocialData": {
        "twitter": "@spiderman",
        "facebook": "facebook.com/spiderman",
        "lastEvent": "2018-06-09T10:30:00",
        "isSpeaker": false
    }
}

GET https://graph.microsoft.com/beta/users/?$select=displayName,inheritscloud_SocialData&$filter=inheritscloud_SocialData/twitter eq '@spiderman'  HTTP/1.1